name: Floxx release
on:
  push:
    branches:
      - master
env:
  REPO_CLEVER: ${{secrets.CLEVER_PROD_REPO}}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v2
   
      - name: add clever branch
        run: 
          git remote add clever $REPO_CLEVER

      - name: move on prod branch
        run: git pull origin master

      - name: push to clever
        run: git push clever master

      - run: echo "ğŸ This job's status is ${{ job.status }}."
