name: Floxx Actions
jobs:
  integration-test-on-push:
    on: [push]
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Integration Test
        run: |
          sbt "httpEngine/IntegrationTest/test"
      - name: Packaging to prod
        run: |
          sbt "httpEngine/dist"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
